server {

  server_name sgt.alexheo.com;

  root /home/ubuntu/sgt-alexheo.com/server/public;

  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api {
    proxy_pass http://localhost:3005;
  }

}
